language: python
python:
  - "3.7"
dist: xenial
matrix:
  include:
  - os: linux
    env: PYTHON=3.7
before_install:
- |
  pip install --progress-bar off poetry
install:
- poetry install
- poetry build
script:
- poetry run pytest --cov-report=term --cov-report=html
